# Generated by Django 3.1.7 on 2021-07-23 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_hub_app', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='choice',
            field=models.CharField(choices=[('T-Shirts', 'T-Shirts'), ('Shirts', 'Shirts'), ('Jeans', 'Jeans'), ('Watches', 'Watches'), ('Saree', 'Saree'), ('Churidhar', 'Churidhar'), ('Skirts', 'Skirts'), ('Dresses', 'Dresses')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='fashion_hub_app.category'),
        ),
    ]
