# Generated by Django 3.1.7 on 2021-07-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_hub_app', '0003_auto_20210723_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='choice',
            new_name='subcategory',
        ),
    ]
