# Generated by Django 3.1.7 on 2021-07-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_hub_app', '0004_auto_20210723_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
