# Generated by Django 3.1.7 on 2021-10-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproducts',
            name='subcategory',
            field=models.CharField(max_length=50),
        ),
    ]
