# Generated by Django 3.1.7 on 2021-10-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_auto_20211027_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproducts',
            name='slug',
            field=models.SlugField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
