# Generated by Django 3.1.7 on 2021-11-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_adminproducts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproducts',
            name='img1',
            field=models.FileField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='adminproducts',
            name='img2',
            field=models.FileField(upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='adminproducts',
            name='img3',
            field=models.FileField(upload_to='pictures'),
        ),
    ]
