# Generated by Django 3.1.7 on 2021-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_auto_20211104_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminproducts',
            name='subcategory',
            field=models.CharField(choices=[('Men-T-Shirts', 'Men-T-Shirts'), ('Shirts', 'Shirts'), ('Men-Jeans', 'Men-Jeans'), ('Women-Jeans', 'Women-Jeans'), ('Men-Watches', 'Men-Watches'), ('Women-Watches', 'Women-Watches'), ('Saree', 'Saree'), ('Churidhar', 'Churidhar'), ('Top', 'Top'), ('boys', 'boys'), ('girls', 'girls')], default='1', max_length=50),
        ),
    ]
