# Generated by Django 3.1.7 on 2021-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20211111_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproducts',
            name='imgg',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
