# Generated by Django 3.1.7 on 2021-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_auto_20211111_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminproducts',
            old_name='imgg',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='img2',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='img3',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
