# Generated by Django 3.1.7 on 2021-11-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_auto_20211111_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminproducts',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='adminproducts',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='adminproducts',
            name='img3',
        ),
    ]
