# Generated by Django 3.1.7 on 2021-11-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_auto_20211112_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproducts',
            name='img1',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='img2',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminproducts',
            name='img3',
            field=models.ImageField(default=1, upload_to='pictures'),
            preserve_default=False,
        ),
    ]
