# Generated by Django 3.1.7 on 2021-11-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_auto_20211112_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminproducts',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
