# Generated by Django 3.1.7 on 2021-11-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_adminproducts_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminproducts',
            name='available',
        ),
    ]
