# Generated by Django 3.1.7 on 2021-09-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_auto_20210906_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
