# Generated by Django 3.1.7 on 2021-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0007_orderz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderz',
            name='cartt',
        ),
        migrations.AddField(
            model_name='orderz',
            name='cartt',
            field=models.ManyToManyField(to='Cart.Items'),
        ),
    ]
