# Generated by Django 3.1.7 on 2021-09-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0009_auto_20210920_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderz',
            name='cartt',
            field=models.CharField(max_length=25),
        ),
    ]
