# Generated by Django 3.1.7 on 2021-09-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0012_auto_20210921_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderz',
            name='cartt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Cart.items'),
        ),
    ]
